### ISSUE TITLE
"The defination of Function"

### ISSUE THREAD

**Issue by NBJY688** [PrakritTyagi/MPC_Target-Tracking_UAV#1]
Hello!! very appreciate your work.i have a question ,what is the defination of the"Function".can you show me it. 
Thanks very much!

**Comment by PrakritTyagi** [comment]
Hi NBJY688,

You must be referring to Function as defined here in casadi docs [Function Object](https://web.casadi.org/docs/#document-function). 

Its an object{object of a class} that maps inputs to output.

For example in;

model = [v*cos(theta)*cos(psi);v*sin(theta)*cos(psi);v*sin(psi);yaw;pitch];

f = Function('f',{states,controls},{model});

The Functtion maps inputs {states,controls}--->{model} .

After defining a Function instance if you give input values it will give output of model values(numerical)l.

**Comment by NBJY688** [comment]
oh,i see!This is a really wonderful job.Thanks so much .Then another question, if i want test a quadcopters,what should i do for the code?

**Comment by PrakritTyagi** [comment]
Yes definitely you could test the simulation for a quadcopter. 

1. Change the Uav model to Quadcopter model.
2.  Change the Constraints 
3. refer this guy for MPC [MMehrez](https://github.com/MMehrez/MPC-and-MHE-implementation-in-MATLAB-using-Casadi)
4. His youtube channel [Casadi Tutorial](https://www.youtube.com/watch?v=RrnkPrcpyEA)

Video and the github of MMehrez for simple problems will help you understand the structure of the code.

**Comment by NBJY688** [comment]
wow,that is wonderful.I really appreciate your replay!!!!Thankyou sou much.Please accept my best wishes for you.

**Comment by PrakritTyagi** [comment]
Thank you very much. Best wishes to you too.
