### ISSUE TITLE
Error in main_Multi_Robot_Tracking_obs_avoid_single_sh (line 35) cascadi 2

### ISSUE THREAD

**Issue by harunkurtdev** [PrakritTyagi/MPC_Target-Tracking_UAV#2]
>> main_Multi_Robot_Tracking_obs_avoid_single_sh
Unable to resolve the name 'SX.sym'.

Error in main_Multi_Robot_Tracking_obs_avoid_single_sh (line 35)

```matlab
x = SX.sym('x'); y = SX.sym('y'); z = SX.sym('z'); theta = SX.sym('theta'); psi = SX.sym('psi');
````

**Comment by PrakritTyagi** [comment]
Since you are getting an issue initially when the symbolic symbols are defined that means Casadi is not added to path or not properly installed. You must also add to path your dev folder.

**Comment by harunkurtdev** [comment]
okey, thank you sir.
Have a nice day.
